[build]
command = "echo 'no op'"
functions = "functions/"
publish = "public"

[build.environment]
NODE_VERSION = "15"

[[redirects]]
from = "/a"
to = "/docs/a"

[[redirects]]
from = "/docs/*"
to = "/docs/b/:splat"
