[build]
command = "echo 'no op'"
functions = "functions"
publish = "public"

[build.environment]
NODE_VERSION = "12"

[[plugins]]
package = "@netlify/plugin-lighthouse"
[plugins.inputs]
output_path = "reports/lighthouse.html"
