name: Update status

on:
  - status

jobs:
  set-status:
    runs-on: ubuntu-latest
    steps:
      - uses: ouzi-dev/commit-status-updater@v1.1.0
        if: contains(github.event.description, 'Deploy Preview canceled')
        with:
          status: 'success'
