name: Update status

on:
  - status

jobs:
  set-status:
    runs-on: ubuntu-latest
    steps:
      - name: update status
        if: contains(github.event.state, 'failure')
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{"state":"success", "context":"${{ github.event.context }}"}' \
          --fail
